# cloudbuild.yaml

steps:
# Step 1: Install Poetry, export dependencies to a requirements.txt, install them, and run tests.
- name: 'python:3.12-slim'
  id: 'Install-and-Test'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    pip install poetry
    # Export dependencies from the lock file to a standard requirements.txt
    poetry export -f requirements.txt --output requirements.txt --without-hashes
    # Install dependencies using pip
    pip install -r requirements.txt
    # Run tests
    pytest -v

# Step 2: Deploy the application code (including the new requirements.txt)
- name: 'gcr.io/cloud-builders/gsutil'
  id: 'Deploy-App-Code'
  args:
  # ... (cette partie reste inchangée, elle synchronise tout le dossier)
  - '-m'
  - 'rsync'
  - '-r'
  - '-c'
  - '-d'
  - '.'
  - 'gs://${_COMPOSER_BUCKET}/data/pharma_graph_pipeline'

# Step 3: Deploy the DAG file
- name: 'gcr.io/cloud-builders/gsutil'
  id: 'Deploy-DAG'
  args:
  # ... (cette partie reste inchangée)
  - '-m'
  - 'rsync'
  - '-c'
  - '-d'
  - 'dags/'
  - 'gs://${_COMPOSER_BUCKET}/dags'